### ISSUE TITLE
Build fails on Linux

### ISSUE THREAD

**Issue by Heawen** [meelgroup/ganak#11]
Hi, 
I failed to build this with the following log. Can you check this out?

`
/ganak-master/build$ cmake 
-- LIB directory is ''
-- BIN directory is ''
-- Doing a RelWithDebInfo build
-- Compiling for dynamic library use
-- build type is RelWithDebInfo
-- Performing Test HAVE_FLAG_-mtune=native
-- Performing Test HAVE_FLAG_-mtune=native - Success
'--'
-- Performing Test HAVE_FLAG_-std=c99
-- Performing Test HAVE_FLAG_-std=c99 - Success
CMake Error at build/CMakeFiles/git-data/grabRef.cmake:36 (file):
  file failed to open for reading (No such file or directory):

   ''xxxxx''/ganak-master/build/CMakeFiles/git-data/head-ref
Call Stack (most recent call first):
  cmake/GetGitRevisionDescription.cmake:70 (include)
  CMakeLists.txt:309 (get_git_head_revision)

-- GIT hash found: 
-- PROJECT_VERSION: 1.0.1
-- PROJECT_VERSION_MAJOR: 1
-- PROJECT_VERSION_MINOR: 0
-- PROJECT_VERSION_PATCH: 1
-- Configuring incomplete, errors occurred!`

**Comment by smsharma1** [comment]
Hi @Heawen,
Thanks for reaching out. Can you please paste the steps you used to compile ganak? I tried the following steps and it worked for me.
1. Clone: git clone https://github.com/meelgroup/ganak.git ganak-issue
2. mkdir build && cd build
3. ../scripts/build_norm.sh 

If you wanna compile the static binary you can use scripts/build_static.sh.

**Comment by Heawen** [comment]
Thanks for your reply. 

> Thanks for reaching out. Can you please paste the steps you used to compile ganak? 
>
My Steps: 
I downloaded ganak-master.zip from github, and :
1. unzip ganak-master.zip 
2. cd ganak-master && mkdir build && cd build
3. cmake ..
Here comes the error report.

I tried 
>../scripts/build_norm.sh
>
and 
>../scripts/build_static.sh
>
but still, error reports:
 file failed to open for reading (No such file or directory):
    *****/ganak-master/build/CMakeFiles/git-data/head-ref

**Comment by Heawen** [comment]
It is built successfully when I clone it from github on Ubuntu. It seems that the ganak.zip downloaded from Windows can't be decompressed and installed directly on Ubuntu.
