### ISSUE TITLE
Disable probabilistic solving in Ganak

### ISSUE THREAD

**Issue by vroland** [meelgroup/ganak#15]
Hi,

I was wondering wether it is possible to use Ganak for exact counting as well. If that's the case, how can I configure it that way? 

Regards,

Valentin

**Comment by kuldeepmeel** [comment]
Please use the following option: "-noPCC			 turn off probabilistic component caching:"

You can see other options

`Usage: ganak [options] [CNF_File]
Options: 
	 -noPP  		 turn off preprocessing
	 -q     		 quiet mode
	 -t [s] 		 set time bound to s seconds
	 -noCC  		 turn off component caching
	 -cs [n]		 set max cache size to n MB
	 -noIBCP		 turn off implicit BCP
	 -noPCC			 turn off probabilistic component caching
	 -seed [n]		 set random seed to n (Default: 1000)
	 -m [n] 		 set the range of hash function (= 64 x n) (Default: 1) 
	 -delta [n] 		 set the confidence parameter to n (Default: 0.05) 
	 -noCSVSADS		 turn off CSVSADS variable branching heuristic
	 -pol [Polarity]	 Polarity: true, false, default, polaritycache (Default: polaritycache)
	 -EDR			 turn on EDR variable branching heuristic
	 -LSO [n]		 learn and start over after n decisions (Default: 5000)
	 -noPMC			 turn off projected model counting 
	 -maxdec [n] [m] 	 terminate after n decision if conflict is less than m 
	
`
