### ISSUE TITLE
Incorrect weighted model count because of learn-and-start-over?

### ISSUE THREAD

**Issue by latower** [meelgroup/ganak#16]
Dear `ganak` developers and maintainers,

I'm running some experiments on the [wmc branch](https://github.com/meelgroup/ganak/tree/wmc) and there is one instance for which the weighted model count returned by `ganak` is twice that of the weighted model count returned by `Cachet`, `ace` (it's an encoding of a Bayesian Network), and my own version of weighted `sharpSAT`.
To be specific: `ganak` returns 1.20932839536671822778, while the other solvers return 0.604664197683359113891.

I have always had the `-noPMC` and `-noPCC` flags, but I have played with different branching heuristics, with always the same result.

However: when I turn LSO off, the weighted model count returned by `ganak` matches the model count returned by the other solvers.

I'm guessing I can for now just work around this problem by disabling LSO for my experiments, but it would be nice to fix this, if it is indeed buggy behaviour, or otherwise just understand it better. Could you maybe help with this? Am I missing or misunderstanding something?

----------------------------------------

A few more thoughts on this problem:

I noticed that any variables for which the weight is unspecified, are interpreted by `ganak` as having weight 1 for each literal.
I also noticed that free variables still contribute to the model count, such that for each free variable for which both literals have weight 1, the model count is multiplied with 2.

As far as I can tell, there are 4 free variables in the instance below:
```
Variable 259 with weight 0.12 is free
Variable 261 with weight 0.45 is free
Variable 263 with weight 0.28 is free
Variable 265 with weight 0.63 is free
```

Since none of them has weight 1, I'm guessing that maybe they are not the cause of the factor 2 discrepancy with the model count returned by the other solvers, but it must be one of the variables with no specified weight?
I haven't seen this discrepancy in any of the other 50 instances that I generated. 

Thanks for reading, and kind regards,
anna

---------------------------------------

The problematic instance: [input2.cnf.gz](https://github.com/meelgroup/ganak/files/8670098/input2.cnf.gz)

**Comment by msoos** [comment]
Hi! Sorry for being so late :( Thanks for the super-detailed information! I will take a look in the next days and see what the problem may be. Your analysis is super-helpful, actually, thank you so much!

**Comment by latower** [comment]
Hi Mate,

Thank you for your response! I was wondering if there may be an update on this issue?

Kind regards,
Anna

**Comment by msoos** [comment]
Hey @smsharma1  do you have an idea why this may be happening?
