### ISSUE TITLE
Please remove dependence on MIS and instead use B+E

### ISSUE THREAD

**Issue by kuldeepmeel** [meelgroup/ganak#4]
It is perhaps better to just distribute the binary for B+E, and remove dependence on MIS.

**Comment by msoos** [comment]
Oh, for sure. @smsharma1 please add the B+E binary instead into the distribution. Please `strip` the binary **before** you add it, so it's smaller. Thanks! Note that if you commit it in, then you strip it and commit it in, then you have not only not reduced the size, but actually made it more than 2x large. The history will contain both versions. So you **must** strip **before** `git add`. Thanks!

**Comment by smsharma1** [comment]
Done!

**Comment by albalkum** [comment]
What project/code is "B + E"/arjun?  I've been working with ganak recently and only just noticed the switch from MIS.  Thanks for the help!

**Comment by kuldeepmeel** [comment]
We are still working on writing the paper for arjun and corresponding open-source release but please feel us to send me an email at meel@comp.nus.edu.sg for more discussion.
B+E is another tool to compute independent support; available here as a binary: http://www.cril.univ-artois.fr/KC/bpe2.html
