### ISSUE TITLE
Dependence on Header.

### ISSUE THREAD

**Issue by priyanka-golia** [meelgroup/ganak#9]
Hi Shubham,

Just an observation:

For a toy example
```
p cnf 2 1 
1 2 0
-1 -2 0
```
Output of GANAK is: 
```
c # solutions 
s mc 3
c # END
```

Whereas with the correct header, as expected, output is 2.

Thanks, 
Priyanka

**Comment by msoos** [comment]
My understanding is that GANAK gives a solution that is only approximately correct?

**Comment by yashpote** [comment]
> My understanding is that GANAK gives a solution that is only approximately correct?

GANAK gives out the _exactly correct_ answer in 1-\delta of the cases and is allowed to be wrong on the remaining \delta.
